on:
  push:
    branches: ["project/1_calculator"]
name: Test Calculator app
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"
          cache: "gradle"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.1"
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter test
